server:
  port: 8082

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unicred
    username: unicred
    password: unicred
  logging:
    level:
      br.com.unicred: error
  flyway:
    enabled: true