# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.2.3
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      -
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run build!
      - run: gradle build

      # prepare docker!
      - setup_remote_docker:
          docker_layer_caching: true

      # login docker registry!
      - run: docker login --username $DOCKER_USER --password $DOCKER_PASSWORD

      # criar imagem docker!
      - run: gradle dockerBuildImagem

      # push imagem docker!
      - run: gradle dockerPushImage

      # export covarege
      - codecov/upload:
          file: ~/repo/build/reports/*
          token: 1276ce30-72ff-4ec2-b7a5-ee4db6021a35